source "https://rubygems.org"

ruby ">= 3.2.0"

gem "rails", "~> 7.2.0"
gem "sqlite3", "~> 2.1"
gem "puma", "~> 6.4"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.8"
gem "rack-cors"
gem "bunny", "~> 2.23"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails", "~> 6.1"
end
